# TEJAPI介紹(1)-資料庫讀取
## 以下文件將說明如何使用TEJ API來存取TEJ 資料庫



### 本次探討的主題分為四大主題:
1. 如何獲取免費版的TEJAPI試用金鑰
2. 如何找到要使用的資料庫
3. TEJAPI資料庫的內建編碼實作
4. 免費板與付費版的差異

![TEJLOGO](https://concert.stpi.narl.org.tw/uploads/system/logo/32/TEJ-logo.jpg)
## 1.獲取TEJAPI的金鑰
請GOOGLE搜尋:開始體驗tej免費資料庫
 + [TEJ金鑰獲取說明](https://www.tejwin.com/insight/%E3%80%90%E6%96%B0%E6%89%8B%E4%B8%8A%E8%B7%AF%E4%BA%94%E3%80%91%E9%96%8B%E5%A7%8B%E9%AB%94%E9%A9%97tej%E5%85%8D%E8%B2%BB%E8%B3%87%E6%96%99%E5%BA%AB/)

## 2. 如何找到要使用的資料庫
#### 請GOOGLE搜尋:TEJAPI資料庫
+ [TEJAPI資料庫](https://api.tej.com.tw/)
+ 以免費的大盤資料做範例

## 3. TEJAPI資料庫的內建編碼實作
請GOOGLE搜尋:TEJAPI資料庫
+ [TEJAPI資料庫](https://api.tej.com.tw/)
+ 最後會說明免費版與付費版之差異

In [1]:
#下載TEJAPI套件
!pip install tejapi

Requirement already satisfied: tejapi in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (0.1.25)
Requirement already satisfied: pandas>=0.18.1 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from tejapi) (1.2.5)
Requirement already satisfied: numpy>=1.8 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from tejapi) (1.23.5)
Requirement already satisfied: requests>=2.7.0 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from tejapi) (2.31.0)
Requirement already satisfied: inflection>=0.3.1 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from tejapi) (0.5.1)
Requirement already satisfied: python-dateutil in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from tejapi) (2.8.2)
Requirement already satisfied: six in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from tejapi) (1.16.0)
Requirement already satisfied: more-itertools in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from tejapi) (10.0.0)
Requirement already satisfied: pytz>=2017.3 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from pandas>=0.18.1->tejapi) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from requests>=2.7.0->tejapi) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from requests>=2.7.0->tejapi) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from requests>=2.7.0->tejapi) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/chenzhaoxiang/anaconda3/envs/zipline-tej/lib/python3.8/site-packages (from requests>=2.7.0->tejapi) (2023.7.22)

- 存取檔案內的api key字串
- 設定ApiConfig將顯示時區的功能取消

In [4]:
# 導入TEJ API的套件
import tejapi
import pandas as pd

with open('key.txt', 'r') as file:
       key = file.read()

# 設定全域變數-登入TEJ API

api_key = 'your tejapi key'
tejapi.ApiConfig.api_key = api_key
# 決定時間欄位是否顯示時區
tejapi.ApiConfig.ignoretz = True
# tejapi.ApiConfig.ignoretz = False

FileNotFoundError: [Errno 2] No such file or directory: 'key.txt'

## 1.抓取資料庫中所有資料
[試用的股票資料庫](https://api.tej.com.tw/columns.html?idCode=TRAIL/TAPRCD)

In [5]:
# 使用資料庫讀取所有資料，要習慣加入'paginate=True'
data = tejapi.get('TRAIL/TAPRCD')

# 展示資料庫的資料
print(data)

KeyboardInterrupt:

## 2.抓取資料庫中特定欄位資料
+ 以股票欄位、時間欄位做說明
+ 可使用陣列的方式輸入公司代碼以一次撈取多筆資料

In [ ]:
# 使用資料庫讀特定的股票資料，我們可以指定要coid欄位為'股票代碼'
# 要選取多個資料可以使用list的方式選取多筆股票['代號','代號']
tax = ['2330', '0050', '00878'] # 建立list

data = tejapi.get('TRAIL/TAPRCD',
                  coid=tax,
                  mdate='2022-01-03',
                  paginate=True)

data

## 3.使用opts來塞選出指定的資料欄位
+ 篩選欄位整理資料
+ 使用opt字典來指定需要撈取的欄位名稱

In [ ]:
# 使用可以加入opts的字典函數來塞選需要的資料欄位的
data = tejapi.get('TRAIL/TAPRCD',
                  coid='0050',
                  mdate='2022-01-03',
                  opts={'columns':['coid','mdate','open_d']},
                  paginate=True)

data = pd.DataFrame(data)

# 展示資料庫的資料
print(data)

## 4.使用mdate中的gte、lte指定資料期間
+ 利用mdate字典來指定撈取資料時間區間

In [ ]:
# 使用mdate字典函數來選定指定日期
data = tejapi.get('TRAIL/TAPRCD',
                  coid='0050',
                  mdate={'gte':'2022-01-03','lte':'2022-02-30'},
                  opts={'columns':['coid','mdate','open_d']},
                  paginate=True)

data = pd.DataFrame(data)

# 展示資料庫的資料
print(data)

## 5.資料欄位改成中文顯示
+ 使用chinese_column_name來將欄位名稱更改為中文顯示
+ 方便閱讀

In [ ]:
# 使用mdate字典函數來選定指定日期
data = tejapi.get('TRAIL/TAPRCD',
                  coid='0050',
                  mdate={'gte':'2022-01-03','lte':'2022-02-30'},
                  opts={'columns':['coid','mdate','open_d']},
                  paginate=True,
                  chinese_column_name=True
                 )

data = pd.DataFrame(data)

# 展示資料庫的資料
print(data)
data.to_csv('data1.csv', index=False, encoding='big5')

## 5. 付費板與免費版的差異
+ 怎麼購買Tejapi的付費資料庫
+ [TEJAPI Eshop資料庫](https://eshop.tej.com.tw/E-Shop/index)

## 看完以下內容，你將會學到:
1. tejapi付費板與免費版之差異
2. 常見的dataframe資料處理

## 1. 本文使用資料庫

本文採用:
 + 單季財務資料表:資料庫代碼為 TWN/EWIFINQ
 + [點此前往Eshop](https://eshop.tej.com.tw/E-Shop/index)
 
## 2. 試用資料庫與付費資料庫的差異
![我的範例圖片](說明1.png)
+ 註解一:我們前面提到可以使用paginate=True來抓取資料庫中的所有資料，而免費版每次傳輸只有1000筆，而付費版每次為10000筆，在資料蒐集部分速度的部分整整差了10倍。
+ 付費版跟免費版每次使用指令後，最高的資料筆數上限為100萬筆
+ pivot轉置功能將使會計科目以更清楚的方式呈現，且格式上更為方便進行資料處理與分析

## 3.導入套件

In [12]:
# 導入TEJ API的套件
import tejapi
with open('key1.txt', 'r') as file:
       key1 = file.read()

# 設定全域變數-登入TEJ API
api_key = key1
tejapi.ApiConfig.api_key = api_key
tejapi.ApiConfig.api_base="http://10.10.10.66"
# 決定時間欄位是否顯示時區
tejapi.ApiConfig.ignoretz = True

## 4. 從付費財務資料庫撈取資料
### 4.1撈取台積電所有季度財務數據

In [56]:
# 因為是付費資料庫，固有所有資料，且資料不用另外調整
finance = tejapi.get('TWN/EWIFINQ',
                  coid='2330',
                  paginate=True,
                  chinese_column_name=True
                 )
finance

,證券碼,財務資料日,季別,合併(Y/N),單季(Q)/單半年(H),月份,幣別,財報發布日,每股盈餘,ROA(C) 稅前息前折舊前,...,合併總損益,歸屬母公司淨利（損）,普通股每股現金股利（盈餘及公積）,普通股每股股票股利－盈餘,普通股每股股票股利－公積,折舊－CFO,攤提－CFO,來自營運之現金流量,投資活動之現金流量,籌資活動之現金流量
None,,,,,,,,,,,,,,,,,,,,,
0,2330,2008-03-01,1,Y,Q,03,NTD,2008-04-29,4.40,35.32,...,28236031.0,28143382.0,None,None,None,19830859.0,0.0,57295397.0,-3125967.0,-3286375.0
1,2330,2008-06-01,2,Y,Q,06,NTD,2008-08-20,4.48,34.68,...,28874006.0,28770506.0,None,None,None,20034419.0,0.0,45050799.0,3596749.0,-6846955.0
2,2330,2008-09-01,3,Y,Q,09,NTD,2008-10-30,4.72,37.96,...,30771587.0,30573504.0,None,None,None,20686089.0,0.0,55903424.0,-26525394.0,-104962021.0
3,2330,2008-12-01,4,Y,Q,12,NTD,2009-03-16,1.92,24.68,...,12641613.0,12445776.0,None,None,None,20960824.0,0.0,63243945.0,18012728.0,-297470.0
4,2330,2009-03-01,1,Y,Q,03,NTD,2009-04-30,0.24,15.36,...,1487727.0,1558873.0,None,None,None,20483463.0,0.0,26788333.0,8136274.0,-7875003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2330,2022-03-01,1,Y,Q,03,NTD,2022-05-13,31.28,35.32,...,202873374.0,202732975.0,None,None,None,108934265.0,2167798.0,372169688.0,-288073791.0,-19086188.0
57,2330,2022-06-01,2,Y,Q,06,NTD,2022-08-12,36.56,37.40,...,237180252.0,237027317.0,None,None,None,111040735.0,2183912.0,338849429.0,-275932106.0,19080454.0
58,2330,2022-09-01,3,Y,Q,09,NTD,2022-11-14,43.32,38.12,...,280968407.0,280865780.0,None,None,None,103147219.0,2198447.0,412698167.0,-284390325.0,-130406753.0
59,2330,2022-12-01,4,Y,Q,12,NTD,2023-02-24,45.64,37.20,...,295878482.0,295904177.0,None,None,None,105375960.0,2205937.0,486881904.0,-342532013.0,-69831545.0
60,2330,2023-03-01,1,Y,Q,03,NTD,2023-05-12,31.92,28.48,...,206949036.0,206986561.0,None,None,None,108083376.0,2239265.0,385244745.0,-272231795.0,-64487030.0

### 4.2 撈取多家公司所有季度、特定財務數據

In [57]:
# 挑選以下幾間公司
coid_list = ['2330','2311','2329','2330','2338']

coid_finance = tejapi.get('TWN/EWIFINQ',
                  coid= coid_list,
                  paginate=True,
                  chinese_column_name=True
                 )
coid_finance

,證券碼,財務資料日,季別,合併(Y/N),單季(Q)/單半年(H),月份,幣別,財報發布日,每股盈餘,ROA(C) 稅前息前折舊前,...,合併總損益,歸屬母公司淨利（損）,普通股每股現金股利（盈餘及公積）,普通股每股股票股利－盈餘,普通股每股股票股利－公積,折舊－CFO,攤提－CFO,來自營運之現金流量,投資活動之現金流量,籌資活動之現金流量
None,,,,,,,,,,,,,,,,,,,,,
0,2311,2008-03-01,1,Y,Q,03,NTD,2008-05-14,1.76,20.44,...,2871193.0,2336712.0,None,None,None,3939992.0,195980.0,7425389.0,-8148309.0,445769.0
1,2311,2008-06-01,2,Y,Q,06,NTD,2008-08-29,1.76,20.48,...,2782791.0,2411489.0,None,None,None,3974830.0,199509.0,6928879.0,-28271466.0,28169828.0
2,2311,2008-09-01,3,Y,Q,09,NTD,2008-11-14,1.64,19.80,...,2376681.0,2211725.0,None,None,None,4121242.0,279668.0,7625789.0,4043503.0,-8700457.0
3,2311,2008-12-01,4,Y,Q,12,NTD,2009-04-28,-0.60,11.80,...,-823182.0,-799874.0,None,None,None,4297451.0,236180.0,8748742.0,-3982895.0,-6052758.0
4,2311,2009-03-01,1,Y,Q,03,NTD,2009-05-15,-1.20,8.96,...,-1596225.0,-1566885.0,None,None,None,4303552.0,241090.0,2399185.0,-1375239.0,-746877.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2338,2022-03-01,1,Y,Q,03,NTD,2022-05-13,-4.56,9.36,...,-313426.0,-244698.0,None,None,None,133840.0,4296.0,-108308.0,-821683.0,404864.0
230,2338,2022-06-01,2,Y,Q,06,NTD,2022-08-12,-6.32,28.68,...,-386011.0,-333098.0,None,None,None,89718.0,16010.0,-198940.0,-820203.0,1130304.0
231,2338,2022-09-01,3,Y,Q,09,NTD,2022-11-14,11.72,44.28,...,541802.0,599552.0,None,None,None,169889.0,14958.0,579905.0,-910249.0,111269.0
232,2338,2022-12-01,4,Y,Q,12,NTD,2023-03-03,13.08,36.32,...,603267.0,681763.0,None,None,None,174746.0,10127.0,1140112.0,-1025552.0,-423257.0
233,2338,2023-03-01,1,Y,Q,03,NTD,2023-05-15,4.04,8.60,...,138878.0,208051.0,None,None,None,199199.0,11570.0,431887.0,-1336840.0,603405.0

In [19]:
#查看資料欄位
coid_finance.columns

Index(['證券碼', '財務資料日', '季別', '合併(Y/N)', '單季(Q)/單半年(H)', '月份', '幣別', '財報發布日',
       '每股盈餘', 'ROA(C) 稅前息前折舊前', 'ROE(A)-稅後', '營業毛利率', '營業利益率', '稅後淨利率',
       'CFO/負債', 'CFO/合併總損益', '現金流量比率', '每股淨值(F)-TSE公告數', '營收成長率', '營業毛利成長率',
       '營業利益成長率', '流動比率', '速動比率', '負債比率', '長期資金適合率(A)', '應收帳款週轉次數', '總資產週轉次數',
       '存貨週轉率(次)', '應收帳款及票據', '存貨', '流動資產', '採權益法之長期股權投資', '不動產廠房及設備',
       '商譽及無形資產合計', '非流動資產', '資產總額', '短期借款', '應付商業本票∕承兌匯票', '一年內到期長期負債',
       '流動負債', '應付公司債－非流動', '銀行借款－非流動', '其他長期借款－非流動', '非流動負債', '負債總額', '股本',
       '保留盈餘', '股東權益總額', '負債及股東權益總額', '營業收入淨額', '營業成本', '營業毛利', '營業費用', '營業利益',
       '營業外收入及支出', '所得稅費用', '合併總損益', '歸屬母公司淨利（損）', '普通股每股現金股利（盈餘及公積）',
       '普通股每股股票股利－盈餘', '普通股每股股票股利－公積', '折舊－CFO', '攤提－CFO', '來自營運之現金流量',
       '投資活動之現金流量', '籌資活動之現金流量'],
      dtype='object')

In [58]:
#塞選出特定欄位
selected_finance = coid_finance[['證券碼','財務資料日','ROA(C) 稅前息前折舊前','營業毛利率','流動資產','現金流量比率']]
selected_finance

       證券碼      財務資料日  ROA(C) 稅前息前折舊前  營業毛利率        流動資產  現金流量比率
None
0     2311 2008-03-01           20.44  24.55  55871843.0   20.88
1     2311 2008-06-01           20.48  24.86  59110670.0   14.49
2     2311 2008-09-01           19.80  24.80  55590901.0   22.28
3     2311 2008-12-01           11.80  16.04  46366851.0   34.62
4     2311 2009-03-01            8.96   4.91  45469916.0   11.09
...    ...        ...             ...    ...         ...     ...
229   2338 2022-03-01            9.36  23.62   7857106.0   -1.60
230   2338 2022-06-01           28.68  30.99   7408005.0   -2.16
231   2338 2022-09-01           44.28  26.18   7275422.0    6.97
232   2338 2022-12-01           36.32  27.18   5903882.0   16.33
233   2338 2023-03-01            8.60  27.31   5436935.0    4.79

[234 rows x 6 columns]

## 5.常用見的財務數據操作

### 5.1使用sort_values()排序

In [67]:
#按照日期排序
sorted_finance = selected_finance.sort_values(by = '財務資料日')
sorted_finance

       證券碼      財務資料日  ROA(C) 稅前息前折舊前  營業毛利率          流動資產  現金流量比率
None
0     2311 2008-03-01           20.44  24.55  5.587184e+07   20.88
112   2330 2008-03-01           35.32  43.71  2.814553e+08   92.36
173   2338 2008-03-01           15.52  22.03  4.405864e+06   28.21
51    2329 2008-03-01            8.20   8.61  5.504066e+06    7.71
174   2338 2008-06-01           13.24  24.81  4.226234e+06   33.02
...    ...        ...             ...    ...           ...     ...
232   2338 2022-12-01           36.32  27.18  5.903882e+06   16.33
50    2311 2022-12-01           45.92  29.76  1.105337e+08   53.51
111   2329 2023-03-01            9.04   9.88  8.451895e+06   -7.47
172   2330 2023-03-01           28.48  56.33  1.995728e+09   44.12
233   2338 2023-03-01            8.60  27.31  5.436935e+06    4.79

[234 rows x 6 columns]

## 5.2使用reset_index(drop=true)重置索引

In [62]:
#因為排序、塞選、刪除部分資料後索引值都會被打亂，所以要重置
final = sorted_finance.reset_index(drop = True)
final

      證券碼      財務資料日  ROA(C) 稅前息前折舊前  營業毛利率          流動資產  現金流量比率
0    2311 2008-03-01           20.44  24.55  5.587184e+07   20.88
1    2330 2008-03-01           35.32  43.71  2.814553e+08   92.36
2    2338 2008-03-01           15.52  22.03  4.405864e+06   28.21
3    2329 2008-03-01            8.20   8.61  5.504066e+06    7.71
4    2338 2008-06-01           13.24  24.81  4.226234e+06   33.02
..    ...        ...             ...    ...           ...     ...
229  2338 2022-12-01           36.32  27.18  5.903882e+06   16.33
230  2311 2022-12-01           45.92  29.76  1.105337e+08   53.51
231  2329 2023-03-01            9.04   9.88  8.451895e+06   -7.47
232  2330 2023-03-01           28.48  56.33  1.995728e+09   44.12
233  2338 2023-03-01            8.60  27.31  5.436935e+06    4.79

[234 rows x 6 columns]